name: Generate Samsung TV Plus Playlist

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'generate_samsung_tvplus.py'
      - '.github/workflows/generate-playlist.yml'

# 👇 ensure this workflow can push commits
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 👇 use the built-in token with write perms from `permissions` above
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate playlist and EPG files
        env:
          REGIONS: 'all'       # e.g. 'us,uk,ca' to limit regions
          GROUPS: ''           # e.g. 'News,Sports'
          INCLUDE_DRM: 'true'
          START_CHNO: '1'
          SORT_BY: 'chno'      # 'chno' or 'name'
        run: python generate_samsung_tvplus.py

      - name: Check if files were generated
        run: |
          ls -la output/
          echo "Playlist file size: $(wc -l < output/samsung_tvplus.m3u) lines"
          echo "EPG file size: $(wc -c < output/samsung_tvplus.xml) bytes"

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update Samsung TV Plus playlist and EPG - $(date -u '+%Y-%m-%d %H:%M:%S') UTC"

          # In case the branch advanced since checkout
          git pull --rebase origin "${GITHUB_REF_NAME:-main}" || true

          # Remote is already authenticated by actions/checkout with the token
          git push origin HEAD:"${GITHUB_REF_NAME:-main}"
      # No need to pass GITHUB_TOKEN here; actions/checkout stored credentials

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samsung-tvplus-files
          path: output/
          retention-days: 30
